[package]
name = "bobdos"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
reqwest = { version = "0.12.8", features = ["json", "gzip"] }
tokio = { version = "1.40.0", features = ["full"] }
